import Head from 'next/head'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import CryptoList from '../components/CryptoList'
import CryptoState from '../context/cryptoState'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Binast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CryptoState>
          <Navbar />
          <Header />
          <CryptoList />
        </CryptoState>
      </div>
    </div>
  )
}
