import Head from 'next/head'
import Navbar from '../components/Navbar'
import Alert from '../components/Alert'
import { Bolt } from '../components/Icons'
import Header from '../components/Header'
import CryptoList from '../components/CryptoList'
import { CryptoProvider } from '../context/cryptoContext'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Binast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CryptoProvider>
          <Alert Icon={Bolt} />
          <Navbar />
          <Header />
          <CryptoList />
        </CryptoProvider>
      </div>
    </div>
  )
}
